title: Alex Cartwright # your name (or website title) here
logo: "/images/cobain.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Environmental Consultant 
  <br><br>
  University of Pennsylvania
  Master of City Planning & Master of Environmental Studies
  <br><br>
  <a href="https://www.linkedin.com/in/aecartwright08/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
